# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarok_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(409, 439)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ime_direktorija = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ime_direktorija.sizePolicy().hasHeightForWidth())
        self.ime_direktorija.setSizePolicy(sizePolicy)
        self.ime_direktorija.setObjectName("ime_direktorija")
        self.horizontalLayout.addWidget(self.ime_direktorija)
        self.izberi_direktorij = QtWidgets.QPushButton(self.tab)
        self.izberi_direktorij.setObjectName("izberi_direktorij")
        self.horizontalLayout.addWidget(self.izberi_direktorij)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(10, 120, 241, 92))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ime_videa = QtWidgets.QLineEdit(self.widget)
        self.ime_videa.setObjectName("ime_videa")
        self.verticalLayout_2.addWidget(self.ime_videa)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.label_image_left = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_left.sizePolicy().hasHeightForWidth())
        self.label_image_left.setSizePolicy(sizePolicy)
        self.label_image_left.setMaximumSize(QtCore.QSize(400, 400))
        self.label_image_left.setTextFormat(QtCore.Qt.PlainText)
        self.label_image_left.setScaledContents(True)
        self.label_image_left.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_image_left.setObjectName("label_image_left")
        self.horizontalLayout_2.addWidget(self.label_image_left)
        self.label_image_right = QtWidgets.QLabel(self.centralwidget)
        self.label_image_right.setEnabled(True)
        self.label_image_right.setMaximumSize(QtCore.QSize(400, 400))
        self.label_image_right.setScaledContents(False)
        self.label_image_right.setObjectName("label_image_right")
        self.horizontalLayout_2.addWidget(self.label_image_right)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.izberi_direktorij.clicked.connect(MainWindow.izberi_direktorij)
        self.pushButton.clicked.connect(MainWindow.generiraj_seznam)
        self.listWidget.itemSelectionChanged.connect(MainWindow.perform_analysis)
        self.listWidget.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.perform_analysis)
        self.pushButton_2.clicked.connect(self.listWidget.clear)
        self.pushButton_3.clicked.connect(MainWindow.setup_camera)
        self.pushButton_4.clicked.connect(MainWindow.stop_timer)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ime_direktorija.setText(_translate("MainWindow", "./set_luka_1/"))
        self.izberi_direktorij.setText(_translate("MainWindow", "Izberi direktorij"))
        self.pushButton_2.setText(_translate("MainWindow", "Izprazni seznam"))
        self.pushButton.setText(_translate("MainWindow", "Naredi seznam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.ime_videa.setText(_translate("MainWindow", "tarok_video.mp4"))
        self.pushButton_3.setText(_translate("MainWindow", "Začni z ogledom"))
        self.pushButton_4.setText(_translate("MainWindow", "Končaj z ogledom"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_image_left.setText(_translate("MainWindow", "TextLabel"))
        self.label_image_right.setText(_translate("MainWindow", "TextLabel"))

