# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarok_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(465, 448)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ime_karte = QtWidgets.QLineEdit(self.centralwidget)
        self.ime_karte.setObjectName("ime_karte")
        self.verticalLayout_3.addWidget(self.ime_karte)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ime_direktorija = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ime_direktorija.sizePolicy().hasHeightForWidth())
        self.ime_direktorija.setSizePolicy(sizePolicy)
        self.ime_direktorija.setObjectName("ime_direktorija")
        self.horizontalLayout.addWidget(self.ime_direktorija)
        self.izberi_direktorij = QtWidgets.QPushButton(self.tab)
        self.izberi_direktorij.setObjectName("izberi_direktorij")
        self.horizontalLayout.addWidget(self.izberi_direktorij)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ending_line = QtWidgets.QLineEdit(self.tab)
        self.ending_line.setObjectName("ending_line")
        self.verticalLayout.addWidget(self.ending_line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ime_videa = QtWidgets.QLineEdit(self.tab_2)
        self.ime_videa.setObjectName("ime_videa")
        self.verticalLayout_2.addWidget(self.ime_videa)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.sleep_time = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sleep_time.sizePolicy().hasHeightForWidth())
        self.sleep_time.setSizePolicy(sizePolicy)
        self.sleep_time.setObjectName("sleep_time")
        self.gridLayout_2.addWidget(self.sleep_time, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.function_time_line = QtWidgets.QLineEdit(self.tab_2)
        self.function_time_line.setAutoFillBackground(False)
        self.function_time_line.setReadOnly(True)
        self.function_time_line.setClearButtonEnabled(False)
        self.function_time_line.setObjectName("function_time_line")
        self.gridLayout_2.addWidget(self.function_time_line, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.video_msec_line = QtWidgets.QLineEdit(self.tab_2)
        self.video_msec_line.setReadOnly(True)
        self.video_msec_line.setObjectName("video_msec_line")
        self.gridLayout_2.addWidget(self.video_msec_line, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_image_left = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_left.sizePolicy().hasHeightForWidth())
        self.label_image_left.setSizePolicy(sizePolicy)
        self.label_image_left.setMaximumSize(QtCore.QSize(300, 300))
        self.label_image_left.setText("")
        self.label_image_left.setTextFormat(QtCore.Qt.PlainText)
        self.label_image_left.setScaledContents(True)
        self.label_image_left.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_image_left.setObjectName("label_image_left")
        self.gridLayout_4.addWidget(self.label_image_left, 0, 0, 1, 1)
        self.label_image_right = QtWidgets.QLabel(self.centralwidget)
        self.label_image_right.setEnabled(True)
        self.label_image_right.setMaximumSize(QtCore.QSize(300, 300))
        self.label_image_right.setText("")
        self.label_image_right.setScaledContents(False)
        self.label_image_right.setObjectName("label_image_right")
        self.gridLayout_4.addWidget(self.label_image_right, 0, 1, 1, 1)
        self.label_image_bottom_left = QtWidgets.QLabel(self.centralwidget)
        self.label_image_bottom_left.setMaximumSize(QtCore.QSize(300, 300))
        self.label_image_bottom_left.setText("")
        self.label_image_bottom_left.setObjectName("label_image_bottom_left")
        self.gridLayout_4.addWidget(self.label_image_bottom_left, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_karta_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_karta_2.setMaximumSize(QtCore.QSize(150, 150))
        self.label_karta_2.setText("")
        self.label_karta_2.setObjectName("label_karta_2")
        self.gridLayout_6.addWidget(self.label_karta_2, 0, 1, 1, 1)
        self.label_karta_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_karta_1.setMaximumSize(QtCore.QSize(150, 150))
        self.label_karta_1.setText("")
        self.label_karta_1.setObjectName("label_karta_1")
        self.gridLayout_6.addWidget(self.label_karta_1, 0, 0, 1, 1)
        self.label_karta_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_karta_3.setMaximumSize(QtCore.QSize(150, 150))
        self.label_karta_3.setText("")
        self.label_karta_3.setObjectName("label_karta_3")
        self.gridLayout_6.addWidget(self.label_karta_3, 1, 0, 1, 1)
        self.label_karta_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_karta_4.setMaximumSize(QtCore.QSize(150, 150))
        self.label_karta_4.setText("")
        self.label_karta_4.setObjectName("label_karta_4")
        self.gridLayout_6.addWidget(self.label_karta_4, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.sleep_time)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.izberi_direktorij.clicked.connect(MainWindow.izberi_direktorij)
        self.pushButton.clicked.connect(MainWindow.generiraj_seznam)
        self.listWidget.itemSelectionChanged.connect(MainWindow.perform_analysis)
        self.listWidget.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.perform_analysis)
        self.pushButton_2.clicked.connect(self.listWidget.clear)
        self.pushButton_3.clicked.connect(MainWindow.setup_camera)
        self.pushButton_4.released.connect(MainWindow.stop_timer)
        self.pushButton_5.clicked.connect(MainWindow.start_timer)
        self.pushButton_6.clicked.connect(MainWindow.display_video_stream)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ime_direktorija.setText(_translate("MainWindow", "./set_luka_1/"))
        self.izberi_direktorij.setText(_translate("MainWindow", "Izberi direktorij"))
        self.ending_line.setText(_translate("MainWindow", ".jpg"))
        self.pushButton_2.setText(_translate("MainWindow", "Izprazni seznam"))
        self.pushButton.setText(_translate("MainWindow", "Naredi seznam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Slike"))
        self.ime_videa.setText(_translate("MainWindow", "tarok_video.mp4"))
        self.pushButton_3.setText(_translate("MainWindow", "Ponastavi Kamero"))
        self.label.setText(_translate("MainWindow", "Zakasnitev časovnika"))
        self.sleep_time.setText(_translate("MainWindow", "100"))
        self.label_2.setText(_translate("MainWindow", "Čas izvajanja obdelave"))
        self.label_3.setText(_translate("MainWindow", "Čas Videa"))
        self.pushButton_5.setText(_translate("MainWindow", "Nadaljuj"))
        self.pushButton_4.setText(_translate("MainWindow", "Ustavi"))
        self.pushButton_6.setText(_translate("MainWindow", "Naslednja slika"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Videi"))

