# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarok_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(477, 409)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ime_direktorija = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ime_direktorija.sizePolicy().hasHeightForWidth())
        self.ime_direktorija.setSizePolicy(sizePolicy)
        self.ime_direktorija.setObjectName("ime_direktorija")
        self.horizontalLayout.addWidget(self.ime_direktorija)
        self.izberi_direktorij = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.izberi_direktorij.setObjectName("izberi_direktorij")
        self.horizontalLayout.addWidget(self.izberi_direktorij)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_image_left = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_left.sizePolicy().hasHeightForWidth())
        self.label_image_left.setSizePolicy(sizePolicy)
        self.label_image_left.setMaximumSize(QtCore.QSize(400, 400))
        self.label_image_left.setTextFormat(QtCore.Qt.PlainText)
        self.label_image_left.setScaledContents(True)
        self.label_image_left.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_image_left.setObjectName("label_image_left")
        self.horizontalLayout_2.addWidget(self.label_image_left)
        self.label_image_right = QtWidgets.QLabel(self.widget)
        self.label_image_right.setEnabled(True)
        self.label_image_right.setMaximumSize(QtCore.QSize(400, 400))
        self.label_image_right.setScaledContents(False)
        self.label_image_right.setObjectName("label_image_right")
        self.horizontalLayout_2.addWidget(self.label_image_right)
        self.verticalLayout_2.addWidget(self.splitter)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.izberi_direktorij.clicked.connect(MainWindow.izberi_direktorij)
        self.pushButton.clicked.connect(MainWindow.generiraj_seznam)
        self.listWidget.itemSelectionChanged.connect(MainWindow.perform_analysis)
        self.pushButton_2.clicked.connect(self.listWidget.clear)
        self.listWidget.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.perform_analysis)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ime_direktorija.setText(_translate("MainWindow", "./set_luka_1/"))
        self.izberi_direktorij.setText(_translate("MainWindow", "Izberi direktorij"))
        self.pushButton_2.setText(_translate("MainWindow", "Izprazni seznam"))
        self.pushButton.setText(_translate("MainWindow", "Naredi seznam"))
        self.label_image_left.setText(_translate("MainWindow", "TextLabel"))
        self.label_image_right.setText(_translate("MainWindow", "TextLabel"))

